name: twoeyes
favicon: null
layout_spectrum: 0.74401
typography_spectrum: 0.22003
title: ii
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#16191e'
    - '#374722'
    - '#9e6b46'
    - '#c3d696'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.8261140959803015
  rhythmicContrast: 0.5967581865843385
purpose: []
