title: ii
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8978494
  brandStrength: 0
  lightness: 0.6451613
  brandColors:
    - '#C6D7E0'
    - '#04ABE9'
    - '#163153'
    - '#87CD07'
    - '#F32220'
  rhythmicContrast: 0.2222222
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: twoeyes
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9229391
layout_spectrum: 1
